function Xist = Area_Import

% Select folder
folderPath = uigetdir(pwd, 'Select folder containing TrackMate track files');

if isequal(folderPath,0)
    error('No folder selected.');
end

% Find csv files
fileList = dir(fullfile(folderPath, '*.csv'));
% sort csv files alphanumeric sort by filename
fileList = natsortfiles(fileList); 

% Import csvs
Xist = cell(1, numel(fileList));
dataLines = [5, Inf];

for k = 1:numel(fileList)
    filePath = fullfile(folderPath, fileList(k).name);
    Xist{k} = importXYZti(filePath, dataLines);

end
end





function C11E2spots = importXYZti(filename, dataLines)
%IMPORTFILE2 Import data from a text file
%  C11E2DOXINT2D1SPOTS = IMPORTFILE2(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  C11E2DOXINT2D1SPOTS = IMPORTFILE2(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  C11E2doxint2D1spots = importfile2("/Users/adamcawte/Documents/MATLAB/Xist Spreading/Data/2D_csvs/C11E2_csvs/C11E2_doxint_2D_1-spots.csv", [5, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 06-Jan-2025 18:37:54

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [5, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 20);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "POSITION_X", "POSITION_Y", "POSITION_Z", "Var8", "FRAME", "Var10", "Var11", "Var12", "MEAN_INTENSITY_CH1", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20"];
opts.SelectedVariableNames = ["POSITION_X", "POSITION_Y", "POSITION_Z", "FRAME", "MEAN_INTENSITY_CH1"];
opts.VariableTypes = ["string", "string", "string", "string", "double", "double", "double", "string", "double", "string", "string", "string", "double", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var8", "Var10", "Var11", "Var12", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var8", "Var10", "Var11", "Var12", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20"], "EmptyFieldRule", "auto");

% Import the data
C11E2spots = readtable(filename, opts);

%% Convert to output type
C11E2spots = table2array(C11E2spots);
end


