function Foci = ImportFoci

% Select folder
folderPath = uigetdir(pwd, 'Select folder containing TrackMate track files');

if isequal(folderPath,0)
    error('No folder selected.');
end

% Find csv files
fileList = dir(fullfile(folderPath, '*.csv'));
% sort csv files alphanumeric sort by filename
fileList = natsortfiles(fileList); 

% Import csvs
Foci = cell(1, numel(fileList));
dataLines = [5, Inf];

for k = 1:numel(fileList)
    filePath = fullfile(folderPath, fileList(k).name);
    Foci{k} = importXYZ(filePath, dataLines);

end
end

function WT3 = importXYZ(filename, dataLines)
%IMPORTFILE2 Import data from a text file
%  WT3 = IMPORTFILE2(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the numeric data.
%
%  WT3 = IMPORTFILE2(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  WT3 = importfile2("/Users/adamcawte/Documents/MATLAB/Data/Xist_Clouds/Clelia/01_24/WT_1.csv", [5, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Jan-2024 17:00:36

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [5, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 20);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "POSITION_X", "POSITION_Y", "POSITION_Z", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20"];
opts.SelectedVariableNames = ["POSITION_X", "POSITION_Y", "POSITION_Z"];
opts.VariableTypes = ["string", "string", "string", "string", "double", "double", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20"], "EmptyFieldRule", "auto");

% Import the data
WT3 = readtable(filename, opts);

%% Convert to output type
WT3 = table2array(WT3);
end