function TS = TS_Import

% Select folder
folderPath = uigetdir(pwd, 'Select folder containing TrackMate track files');

if isequal(folderPath,0)
    error('No folder selected.');
end

% Find csv files
fileList = dir(fullfile(folderPath, '*.csv'));
% sort csv files alphanumeric sort by filename
fileList = natsortfiles(fileList); 

% Import csvs
TS = cell(1, numel(fileList));
dataLines = [5, Inf];

for k = 1:numel(fileList)
    filePath = fullfile(folderPath, fileList(k).name);
    TS{k} = importTrFrInt(filePath, dataLines);

end
end



function spots = importTrFrInt(filename, dataLines)
%IMPORTFILE2 Import data from a text file
%  G9SPENKO75MS01SPOTS = IMPORTFILE2(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  G9SPENKO75MS01SPOTS = IMPORTFILE2(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  G9SpenKO75ms01spots = importfile2("/Users/adamcawte/Desktop/G9_SpenKO_75ms_01-spots.csv", [5, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 27-Jan-2025 19:54:49

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [5, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 20);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "TRACK_ID", "Var4", "Var5", "Var6", "Var7", "Var8", "FRAME", "Var10", "Var11", "Var12", "MEAN_INTENSITY_CH1", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20"];
opts.SelectedVariableNames = ["TRACK_ID", "FRAME", "MEAN_INTENSITY_CH1"];
opts.VariableTypes = ["string", "string", "double", "string", "string", "string", "string", "string", "double", "string", "string", "string", "double", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var4", "Var5", "Var6", "Var7", "Var8", "Var10", "Var11", "Var12", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var4", "Var5", "Var6", "Var7", "Var8", "Var10", "Var11", "Var12", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20"], "EmptyFieldRule", "auto");

% Import the data
spots = readtable(filename, opts);

%% Convert to output type
spots = table2array(spots);
end

